// Regenerates IMAGES_NEEDED.md from the real page data.
// Run with: node scripts/images-needed.mjs
import { writeFileSync } from "node:fs";
import { SERVICES } from "../src/content/services.mjs";
import { CITIES } from "../src/content/cities.mjs";
import { POSTS } from "../src/content/blog.mjs";
import { resolveShot } from "../src/templates/image.mjs";

const rows = [];
const add = (page, group, name, size, shotIdea, alt) =>
  rows.push({ page, group, name, size, shotIdea, alt, have: Boolean(resolveShot(group, name)) });

add(
  "Homepage hero",
  "hero",
  "hero",
  "2000x1200",
  "Truck and crew on a residential job, wide shot with open sky. Darkened behind the headline, so keep the left third uncluttered.",
  "Background image, no alt needed"
);
add(
  "Homepage, Why Us",
  "why-us",
  "crew",
  "1600x700",
  "Crew and truck on site, people visible and in uniform.",
  "Our crew and truck on a job in the Truckee Meadows"
);
for (const s of SERVICES) {
  add(
    `Service: ${s.label}`,
    "services",
    s.slug,
    "1200x800",
    "Work in progress or a finished result for this service. Before and after pairs work well.",
    s.shotAlt
  );
}
for (const c of CITIES) {
  add(`City: ${c.label}`, "cities", c.slug, "1200x800", `Recognisable ${c.label} property or streetscape with our crew or truck in frame.`, c.shotAlt);
}
for (const p of POSTS) {
  add(`Blog: ${p.h1}`, "blog", p.slug, "1200x675", "Header image matching the topic. Real job photography, not stock.", p.shotAlt);
}

const missing = rows.filter((r) => !r.have);
const md = `# Images needed

Generated by \`node scripts/images-needed.mjs\`. Do not edit by hand.

Drop files into \`images/<folder>/<name>.<ext>\`. Accepted extensions, in order of
preference: \`.webp\`, \`.jpg\`, \`.jpeg\`, \`.png\`. WebP is preferred for photographs.
Nothing else needs changing: each slot picks up its file on the next build, and
until then it shows a neutral placeholder at the right shape.

**Status: ${rows.length - missing.length} of ${rows.length} slots filled.**

## Shooting notes

- Real jobs in our service area, no stock photography.
- Landscape orientation, shot wide enough to crop to the sizes below.
- Before and after pairs are welcome for service pages: supply as one combined image.
- Faces of customers or identifiable homes need permission before we publish them.
- If the finished photo differs from the suggested alt text below, tell us and we will rewrite it.

## Slots

| Page | File | Target size | Shot | Suggested alt text | Have it? |
| --- | --- | --- | --- | --- | --- |
${rows
  .map((r) => `| ${r.page} | \`images/${r.group}/${r.name}.webp\` | ${r.size} | ${r.shotIdea} | ${r.alt} | ${r.have ? "yes" : "no"} |`)
  .join("\n")}
`;

writeFileSync("IMAGES_NEEDED.md", md);
console.log(`Wrote IMAGES_NEEDED.md: ${rows.length} slots, ${missing.length} still to shoot.`);
