// Regenerates IMAGES_NEEDED.md from the real page data.
// Run with: node scripts/images-needed.mjs
import { writeFileSync } from "node:fs";
import { SERVICES } from "../src/content/services.mjs";
import { CITIES } from "../src/content/cities.mjs";
import { POSTS } from "../src/content/blog.mjs";
import { resolveShot } from "../src/templates/image.mjs";

const rows = [];
const add = (page, group, name, size, shotIdea, alt, kind) =>
  rows.push({ page, group, name, size, shotIdea, alt, kind, have: Boolean(resolveShot(group, name)) });

add(
  "Homepage hero",
  "hero",
  "reno-skyline",
  "1920x1080",
  "Daytime Reno skyline with the mountains behind it, shot wide. The left third sits under a pale wash and carries the headline, so keep it free of detail. A hi-res replacement for the current 1500px file is wanted.",
  "Decorative, no alt needed",
  "Regional scenery"
);
add(
  "Homepage, Why Us",
  "why-us",
  "crew",
  "900x1100",
  "Crew at work on a property, people visible and in uniform. Portrait or square crops best: it sits in a rounded slot beside the Why Us tiles and stays hidden until this file exists.",
  "Our crew and truck on a job in the Truckee Meadows",
  "Real job photography"
);
add(
  "Driveway Makeover Contest, hero",
  "contest",
  "spa-driveway",
  "2400x1350 wide (16:9) preferred; the current file is 1376x768 (.webp plus a .jpg fallback)",
  "The spa driveway mascot in the wide Lake Tahoe scene, mascot about two thirds across, calm sky and lake on the left. No badge or text baked in. It runs behind the whole hero and fades out behind the headline. A larger version would look sharper on wide screens.",
  "A driveway in a towel and cucumber slices enjoying a spa day",
  "Campaign artwork"
);
add(
  "Driveway Makeover Contest, badge",
  "contest",
  "driveway-makeover-badge",
  "360x360, shown at 180px",
  "The round contest badge on a transparent background.",
  "Decorative, no alt needed (the eyebrow carries the same words)",
  "Campaign artwork"
);
add(
  "Driveway Makeover Contest, Driveway glow-ups row (before)",
  "gallery/compare",
  "driveway-before",
  "1200x900 (4:3 landscape, .webp)",
  "A real customer driveway in our service area before cleaning: oil, tire marks or de-icer film clearly visible. Shot from the same spot as the after photo.",
  "Stained concrete driveway before cleaning",
  "Real job photography"
);
add(
  "Driveway Makeover Contest, Driveway glow-ups row (after)",
  "gallery/compare",
  "driveway-after",
  "1200x900 (4:3 landscape, .webp)",
  "The same driveway after cleaning, same angle and framing as the before. Once both exist they show as one before and after card in the row.",
  "The same driveway after cleaning",
  "Real job photography"
);
add(
  "Driveway Makeover Contest, social share",
  "contest",
  "og-contest",
  "1200x630 (.jpg)",
  "Open Graph image for shares and link previews.",
  "Not shown on the page",
  "Campaign artwork"
);
for (const s of SERVICES) {
  add(
    `Service: ${s.label}`,
    "services",
    s.slug,
    "1200x800",
    "Work in progress or a finished result for this service. Before and after pairs work well.",
    s.shotAlt,
    "Real job photography"
  );
}
for (const c of CITIES) {
  add(`City: ${c.label}`, "cities", c.slug, "1200x800", `Recognisable ${c.label} property or streetscape, ideally with our crew or truck in frame.`, c.shotAlt, "Real job photography, or regional scenery if no job shot exists");
}
for (const p of POSTS) {
  add(`Blog: ${p.h1}`, "blog", p.slug, "1200x675", "Header image matching the topic.", p.shotAlt, "Real job photography");
}

const missing = rows.filter((r) => !r.have);
const md = `# Images needed

Generated by \`node scripts/images-needed.mjs\`. Do not edit by hand.

Drop files into \`images/<folder>/<name>.<ext>\`. Accepted extensions, in order of
preference: \`.webp\`, \`.jpg\`, \`.jpeg\`, \`.png\`. WebP is preferred for photographs.
Nothing else needs changing: each slot picks up its file on the next build, and
until then it shows a neutral placeholder at the right shape.

**Status: ${rows.length - missing.length} of ${rows.length} slots filled.**

## Already covered

- **Homepage gallery:** filled with 13 client supplied photos and videos in
  \`images/gallery/\`. Add more by dropping files there and listing them in the
  GALLERY array in \`src/content/pages.mjs\`.
- **Team or About portrait:** wanted, but there is no About page yet. Once that
  page exists the slot is \`images/why-us/team.webp\` at 1200x800, real job
  photography of the family and crew.

## Shooting notes

- Real jobs in our service area, no stock photography.
- Landscape orientation, shot wide enough to crop to the sizes below.
- Before and after pairs are welcome for service pages: supply as one combined image.
- Faces of customers or identifiable homes need permission before we publish them.
- If the finished photo differs from the suggested alt text below, tell us and we will rewrite it.

## Slots

| Page | File | Target size | Shot | Type | Suggested alt text | Have it? |
| --- | --- | --- | --- | --- | --- | --- |
${rows
  .map((r) => `| ${r.page} | \`images/${r.group}/${r.name}.webp\` | ${r.size} | ${r.shotIdea} | ${r.kind} | ${r.alt} | ${r.have ? "yes" : "no"} |`)
  .join("\n")}
`;

writeFileSync("IMAGES_NEEDED.md", md);
console.log(`Wrote IMAGES_NEEDED.md: ${rows.length} slots, ${missing.length} still to shoot.`);
